// src/components/ui/SecondaryButton.tsx
import React from 'react';
import { TouchableOpacity, Text, ActivityIndicator } from 'react-native';
import { COLORS } from '../../constants/theme';

interface SecondaryButtonProps {
  title: string;
  onPress: () => void;
  loading?: boolean;
  disabled?: boolean;
  className?: string;
}

export const SecondaryButton = ({ title, onPress, loading, disabled, className }: SecondaryButtonProps) => {
  return (
    <TouchableOpacity
      onPress={onPress}
      disabled={loading || disabled}
      className={`py-4 px-6 rounded-2xl flex-row justify-center items-center border border-blue-600 ${className || ''}`}
      style={{ opacity: loading || disabled ? 0.5 : 1 }}
    >
      {loading ? <ActivityIndicator color={COLORS.primary} /> : (
        <Text className="text-blue-600 font-bold text-lg text-center">{title}</Text>
      )}
    </TouchableOpacity>
  );
};

// resources/js/Components/ui/SecondaryButton.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useMergedClass } from '../../composables/useMergedClass';
import Spinner from './Spinner.vue';

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    title: string;
    loading?: boolean;
    disabled?: boolean;
    type?: 'button' | 'submit';
  }>(),
  { loading: false, disabled: false, type: 'button' },
);

const inactive = computed(() => props.loading || props.disabled);

const { classes, rest } = useMergedClass(() => [
  'w-full py-4 px-6 rounded-2xl flex flex-row justify-center items-center border border-blue-600 font-bold text-lg text-blue-600 transition-colors hover:bg-blue-50',
  inactive.value && 'opacity-50 cursor-not-allowed hover:bg-transparent',
]);
</script>

<template>
  <button v-bind="rest" :type="type" :disabled="inactive" :class="classes">
    <Spinner v-if="loading" class="text-blue-600" />
    <span v-else>{{ title }}</span>
  </button>
</template>
