// src/components/ui/Timeline.tsx
import React from 'react';
import { View, Text, Image } from 'react-native';
import { COLORS } from '../../constants/theme';

interface TimelineItem {
  id: string;
  date: string;
  title: string;
  description: string;
  photos?: string[];
  attachments?: string[];
}

interface TimelineProps {
  items: TimelineItem[];
}

export const Timeline = ({ items }: TimelineProps) => {
  return (
    <View className="px-1">
      {items.map((item, index) => (
        <View key={item.id} className="mb-6 flex-row">
          <View className="items-center mr-4">
            <View className="w-4 h-4 rounded-full bg-blue-600 border-2 border-white" style={{ elevation: 2 }} />
            {index !== items.length - 1 && (
              <View className="w-0.5 flex-1 bg-slate-200 mt-1" style={{ minHeight: 60 }} />
            )}
          </View>

          <View className="flex-1 bg-white rounded-2xl p-4 shadow-sm" style={{ shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.05, shadowRadius: 8, elevation: 2 }}>
            <View className="flex-row justify-between mb-2">
              <Text className="text-slate-800 font-bold">{item.title}</Text>
              <Text className="text-slate-400 text-xs">{item.date}</Text>
            </View>
            <Text className="text-slate-600 leading-5 mb-3">{item.description}</Text>

            {item.photos && item.photos.length > 0 && (
              <View className="flex-row flex-wrap gap-2 mb-2">
                {item.photos.map((photo, i) => (
                  <Image key={i} source={{ uri: photo }} className="w-20 h-20 rounded-xl" resizeMode="cover" />
                ))}
              </View>
            )}

            {item.attachments && item.attachments.length > 0 && (
              <View className="flex-row flex-wrap gap-2">
                {item.attachments.map((file, i) => (
                  <View key={i} className="flex-row items-center bg-slate-100 px-3 py-1.5 rounded-lg">
                    <Text className="text-slate-500 text-xs mr-1">📄</Text>
                    <Text className="text-slate-600 text-xs">{file}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>
        </View>
      ))}
    </View>
  );
};

// resources/js/Components/ui/Timeline.vue
<script setup lang="ts">
import type { TimelineItem } from '../../types';

defineProps<{ items: TimelineItem[] }>();
</script>

<template>
  <div class="px-1">
    <div v-for="(item, index) in items" :key="item.id" class="mb-6 flex flex-row">
      <div class="flex flex-col items-center mr-4">
        <div class="w-4 h-4 rounded-full bg-blue-600 border-2 border-white shadow" />
        <div v-if="index !== items.length - 1" class="w-0.5 flex-1 bg-slate-200 mt-1 min-h-[60px]" />
      </div>

      <div class="flex-1 bg-white rounded-2xl p-4 shadow-[0_2px_8px_rgba(0,0,0,0.05)]">
        <div class="flex flex-row justify-between mb-2">
          <p class="text-slate-800 font-bold">{{ item.title }}</p>
          <p class="text-slate-400 text-xs">{{ item.date }}</p>
        </div>
        <p class="text-slate-600 leading-5 mb-3">{{ item.description }}</p>

        <div v-if="item.photos?.length" class="flex flex-row flex-wrap gap-2 mb-2">
          <img
            v-for="(photo, i) in item.photos"
            :key="i"
            :src="photo"
            :alt="`Foto ${i + 1} de ${item.title}`"
            class="w-20 h-20 rounded-xl object-cover"
          />
        </div>

        <div v-if="item.attachments?.length" class="flex flex-row flex-wrap gap-2">
          <span
            v-for="(file, i) in item.attachments"
            :key="i"
            class="flex flex-row items-center bg-slate-100 px-3 py-1.5 rounded-lg"
          >
            <span class="text-slate-500 text-xs mr-1" aria-hidden="true">📄</span>
            <span class="text-slate-600 text-xs">{{ file }}</span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>
