// resources/js/Components/ui/Toast.vue
<script setup lang="ts">
import { onBeforeUnmount, watch } from 'vue';

const props = withDefaults(
  defineProps<{
    message: string;
    type?: 'success' | 'error' | 'info';
    /** Milissegundos até esconder sozinho. */
    duration?: number;
  }>(),
  { type: 'info', duration: 3000 },
);

const visible = defineModel<boolean>('visible', { default: false });

const BG_MAP = {
  success: 'bg-green-500',
  error: 'bg-red-500',
  info: 'bg-blue-600',
} as const;

let timer: ReturnType<typeof setTimeout> | undefined;

function clear() {
  if (timer) clearTimeout(timer);
  timer = undefined;
}

watch(visible, (value) => {
  clear();
  if (value) {
    timer = setTimeout(() => {
      visible.value = false;
    }, props.duration);
  }
});

onBeforeUnmount(clear);
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition duration-300 ease-out"
      enter-from-class="opacity-0 -translate-y-4"
      leave-active-class="transition duration-200 ease-in"
      leave-to-class="opacity-0 -translate-y-4"
    >
      <div
        v-if="visible"
        role="status"
        aria-live="polite"
        :class="['fixed top-16 left-6 right-6 mx-auto max-w-md px-4 py-3 rounded-2xl shadow-lg z-50', BG_MAP[type]]"
      >
        <p class="text-white font-medium text-center">{{ message }}</p>
      </div>
    </Transition>
  </Teleport>
</template>

// src/components/ui/Toast.tsx
import React, { useEffect } from 'react';
import { View, Text } from 'react-native';
import { COLORS } from '../../constants/theme';

interface ToastProps {
  message: string;
  type?: 'success' | 'error' | 'info';
  visible: boolean;
  onHide?: () => void;
}

const BG_MAP = {
  success: 'bg-green-500',
  error: 'bg-red-500',
  info: 'bg-blue-600',
};

export const Toast = ({ message, type = 'info', visible, onHide }: ToastProps) => {
  useEffect(() => {
    if (visible) {
      const timer = setTimeout(() => onHide?.(), 3000);
      return () => clearTimeout(timer);
    }
  }, [visible]);

  if (!visible) return null;

  return (
    <View className={`absolute top-16 left-6 right-6 px-4 py-3 rounded-2xl shadow-lg z-50 ${BG_MAP[type]}`}>
      <Text className="text-white font-medium text-center">{message}</Text>
    </View>
  );
};
